name: Check

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Yarn PnP Setup
        uses: Araxeus/setup-yarn-pnp-action@v1

      - name: Run Checks
        run: yarn check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build
        run: yarn build
