name: Check

on:
  - push
  - pull_request

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Yarn PnP Setup
        uses: Araxeus/setup-yarn-pnp-action@v1

      - name: Run Checks
        run: yarn check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build
        run: yarn build
